name: Unit Testing
on: push
jobs:
        test:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v3
                        - name: set up python
                          uses: actions/setup-python@v2
                          with:
                                 python-version: 3.11
                        - name: Install dependencies
                          run: python -m pip install --upgrade pip
                               pip install pdm
                               pdm install

                        - name: Run tests with pytest
                          run: pdm run pytest --cov=mongo-server

                        - name: Upload coverage to codecov
                          uses: codecov/codecov-action@v3
                          with:
                                  token: ${{ secrets.CODECOV_TOKEN }}
