name: Unit Testing
on: push
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: set up python
          uses: actions/setup-python@v5.1.0
          with:
                 python-version: 3.11
        - name: Setup PDM
          uses: pdm-project/setup-pdm@v4
          with:
                  python-version: 3.11
                  cache: true
        - name: Install dependencies
          run: pdm install

        - name: Run tests with pytest
          run: pdm run pytest --cov=./src/ --cov-fail-under=100

        - name: Upload coverage to codecov
          uses: codecov/codecov-action@v4.3.0
          with:
                  token: ${{ secrets.CODECOV_TOKEN }}
